Repository traefik-workshops/traefik-hub-gitops, pull requests merged in 2024-02, with the labels that each got.

#44 fix: api-server request on path
  api-server/go.mod
  api-server/go.sum
  api-server/main.go
Labels: bug

#42 feat: use public image
  apps/base/apps/customers/api-versioned.yaml
  apps/base/apps/customers/api.yaml
  apps/base/apps/customers/customer-v2.yaml
  apps/base/apps/customers/customer-v3.yaml
  apps/base/apps/customers/customer-v4.yaml
  apps/base/apps/customers/customer.yaml
  apps/base/apps/employee/api.yaml
  apps/base/apps/employee/employee.yaml
  apps/base/apps/flight/api.yaml
  apps/base/apps/flight/flight.yaml
  apps/base/apps/ticket/api.yaml
  apps/base/apps/ticket/ticket.yaml
Labels: enhancement

#36 feat: update helm chart version
  apps/base/apps/customers/api-versioned.yaml
  apps/base/traefik-hub/release.yaml
Labels: enhancement, no-merge
